apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: 2020-10-19T21:52:54Z
  labels:
    app: spring-boot-data-jpa-mysql
  name: spring-boot-data-jpa-mysql
  namespace: spring-boot-data-jpa-mysql
  resourceVersion: "15586"
  selfLink: /apis/build.openshift.io/v1/namespaces/spring-boot-data-jpa-mysql/buildconfigs/spring-boot-data-jpa-mysql
  uid: 71185dd6-1255-11eb-87f5-0242ac110002
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: spring-boot-data-jpa-mysql:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/samyabikash/spring-boot-data-jpa-mysql.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: springboot-maven3-centos:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: -WvAZmWfyTckLofi-bj4
    type: GitHub
  - generic:
      secret: G8s27VBi2bTNWB3_pj1p
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: codecentric/springboot-maven3-centos@sha256:91ecee201c42cfde8616dfe7b5c77c4f6100f95f50c6e8ffe16a78c99dde59bf
    type: ImageChange
status:
  lastVersion: 1
